### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by onecentlin** [recca0120/terminal#4]
<img width="504" alt="screenshot 2015-11-13 15 25 19" src="https://cloud.githubusercontent.com/assets/7122270/11140958/486a048a-8a1b-11e5-871e-773b9eec2eb6.png">

Error Message:

> Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Any idea?

**Comment by recca0120** [comment]
http://stackoverflow.com/questions/26261001/warning-about-http-raw-post-data-being-deprecated

you can download lastest version,
